### ISSUE TITLE
ユーザーネームで現在のポイントゲットしようとすると取得できない

### ISSUE THREAD

**Issue by keix1** [inody/mimaco#10]
子供を見つけたときのPOST処理をusernameで指定するよう変更したので他の処理と通信できなくなっています。
以下のような特定ユーザーの情報
```
  {
    "email": "me@mail.com", 
    "point": 9, 
    "username": "me"
  }
```

を返すGETの方もidではなくusernameで指定するように変更してほしいです。(@app.route("/user/<id>", methods=["GET"])

以下のAPIを叩きます。
/user/me

**Comment by inody** [comment]
修正しました！
